name: sdd-demo-app

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      SPRING_MONGODB_URI: mongodb://mongodb:27017/sdddemo
    depends_on:
      - mongodb

  mongodb:
    image: 'mongo:8.0'
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
